-- printify_products was missing a column to persist the brand-colored SVG
-- mockup generated by src/lib/mockup-generator.ts. Without it, the product-
-- creation endpoints only stored the raw Printify catalog stock photo
-- (image_url), so every created storefront (e.g. google.com) displayed
-- generic photos with no brand logo/colors baked in — normalizeStoredProduct
-- (src/lib/printify-catalog.ts) reads mockup_image_url first and always fell
-- back to the generic image_url because this column never existed.
ALTER TABLE printify_products
  ADD COLUMN IF NOT EXISTS mockup_image_url text;
